using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reactive.Linq;
using System.Text;
using Akavache;
using Akavache.Sqlite3;
using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using RehmaniQaidaApp.Droid.Extensions;
using RehmaniQaidaApp.Extensions;
using Splat;
using Xamarin.Forms;

